### ISSUE TITLE
Doesn't seem to work in 1.13.1 getting these errors when attempting to use region titles plugin

### ISSUE THREAD

**Issue by axemwa** [mewin/WorldGuard-Region-Events#16]
https://pastebin.com/BLwwSXJb

**Comment by harryoui** [comment]
I am getting the same error:
`Could not pass event PlayerJoinEvent to WorldGuard v7.0.0-beta01;01dfebe
java.lang.NoSuchMethodError`

as well as
`Could not pass event PlayerTeleportEvent to WorldGuard v7.0.0-beta01;01dfebe
java.lang.NoSuchMethodError:`
